### ISSUE TITLE
Data Table Eventi

### ISSUE THREAD

**Issue by AntonioLegnante** [AntonioLegnante/Web-Community#1]
@FabioZTessitore #eventi.sql  #index.js La data immessa con una sintassi testata in altri db non viene riconosciuta nè dal database, nè dall'Applicazione Web

**Comment by FabioZTessitore** [comment]
devi passare una stringa in uno dei formati riconosciuti, ad esempio
```
DATE('2018-11-01')
```

**Comment by AntonioLegnante** [comment]
non funziona un gatto  con le modifiche proposte... Managgia Cristoforo Colombo @FabioZTessitore
